### ISSUE TITLE
添加MongoDB数据源报错，MongoDB版本号为5.01.2

### ISSUE THREAD

**Issue by ZYPCSJ** [datavane/tis#254]
``` shell
java.lang.IllegalStateException
	at com.qlangtech.tis.plugin.ds.mangodb.MangoDBDataSourceFactory.getDbConfig(MangoDBDataSourceFactory.java:142)
	at com.qlangtech.tis.plugin.ds.DataSourceFactory$BaseDataSourceFactoryDescriptor.validateDSFactory(DataSourceFactory.java:432)
	at com.qlangtech.tis.plugin.ds.DataSourceFactory$BaseDataSourceFactoryDescriptor.verify(DataSourceFactory.java:423)
	at com.qlangtech.tis.extension.Descriptor$3.visit(Descriptor.java:621)
	at com.qlangtech.tis.extension.Descriptor$3.visit(Descriptor.java:609)
	at com.qlangtech.tis.extension.impl.RootFormProperties.accept(RootFormProperties.java:75)
	at com.qlangtech.tis.extension.Descriptor.verify(Descriptor.java:609)
	at com.qlangtech.tis.util.AttrValMap.validate(AttrValMap.java:100)
	at com.qlangtech.tis.coredefine.module.action.PluginAction.parsePluginItems(PluginAction.java:869)
	at com.qlangtech.tis.coredefine.module.action.PluginAction.doSavePluginConfig(PluginAction.java:785)
	at sun.reflect.GeneratedMethodAccessor224.invoke(Unknown Source)
```

**Comment by baisui1981** [comment]
收到

**Comment by baisui1981** [comment]
做了如下改造：
1. 支持 reader端（例如：MySQL库）多表导入到 mongo的多个collection中。
2. 支持 Mongo reader中 将某个Document类型的field （使用 [jsonpath](https://github.com/json-path/JsonPath)  ）将内部的key->val 拆解，flatmap到目标端的多个字段中

**Comment by baisui1981** [comment]
mongo cdc 技术文章 https://mp.weixin.qq.com/s/Ls0kv6hPuiruU18W8y9o_g

**Comment by PittYao** [comment]
> mongo cdc 技术文章： https://mp.weixin.qq.com/s/Ls0kv6hPuiruU18W8y9o_g mongo reader datax： https://github.com/alibaba/DataX/blob/master/mongodbreader/doc/mongodbreader.md

添加mongo有同样的问题。3.8.0什么时候发布，期待

**Comment by baisui1981** [comment]
> > mongo cdc 技术文章： https://mp.weixin.qq.com/s/Ls0kv6hPuiruU18W8y9o_g mongo reader datax： https://github.com/alibaba/DataX/blob/master/mongodbreader/doc/mongodbreader.md
> 
> 添加mongo有同样的问题。3.8.0什么时候发布，期待

预发布的时候 通知你测试，可以留个微信不？@PittYao
