### ISSUE TITLE
mysql to mysql任务执行失败，

### ISSUE THREAD

**Issue by zerolbsony** [datavane/tis#259]
<img width="1249" alt="截屏2023-09-02 上午11 44 13" src="https://github.com/datavane/tis/assets/5180779/af81e804-7e4c-4179-a8e9-fd311d0fe0f7">
<img width="1267" alt="截屏2023-09-02 上午11 43 59" src="https://github.com/datavane/tis/assets/5180779/2cd1f2ad-a127-4def-b1cf-5b8c568eebc9">
<img width="886" alt="截屏2023-09-02 上午11 43 44" src="https://github.com/datavane/tis/assets/5180779/cc2bda0b-a2f0-4c1d-8819-da1f3c5180cf">
<img width="1027" alt="截屏2023-09-02 上午11 43 16" src="https://github.com/datavane/tis/assets/5180779/5014f14b-76d3-4963-89ef-9cfe93b27e79">

[以下是实时日志；
``` shell
09-02 10:32 start component:FullDump,end component:FullDump
09-02 10:32 component description:
09-02 10:32 JOIN:0
09-02 10:32 FullDump:0
09-02 10:32 description end
09-02 10:32 execute [join,dump]:0[0,0]
09-02 10:32 phase:[join,dump] start ,taskid:4
09-02 10:32 Scout-loading ExtensionList: class com.qlangtech.tis.extension.Descriptor
09-02 10:32 target xstream file is not exist:/home/nero/workspace/java/tis-uber/data/cfg_repo/tis_plugin_config/jobworker/datax-worker/com.qlangtech.tis.datax.job.DataXJobWorker.xml
09-02 10:32 target xstream file is not exist:/home/nero/workspace/java/tis-uber/data/cfg_repo/tis_plugin_config/jobworker/datax-worker/com.qlangtech.tis.datax.job.DataXJobWorker.xml
09-02 10:32 Scout-loading ExtensionList: class com.qlangtech.tis.datax.DataXJobSubmit
09-02 10:32 dataX Job:oe_order_0.json,classpath:/home/nero/workspace/java/tis-uber/tis-assemble/lib/*:/home/nero/workspace/java/tis-uber/data/libs/plugins/tis-datax-local-executor/WEB-INF/lib/*:/home/nero/workspace/java/tis-uber/tis-assemble/conf:/home/nero/workspace/java/tis-uber/web-start/lib/*,workingDir:.
09-02 10:32 dataX Job:oe_stu_course_order_1.json,classpath:/home/nero/workspace/java/tis-uber/tis-assemble/lib/*:/home/nero/workspace/java/tis-uber/data/libs/plugins/tis-datax-local-executor/WEB-INF/lib/*:/home/nero/workspace/java/tis-uber/tis-assemble/conf:/home/nero/workspace/java/tis-uber/web-start/lib/*,workingDir:.
09-02 10:32 dataX Job:oe_stu_course_2.json,classpath:/home/nero/workspace/java/tis-uber/tis-assemble/lib/*:/home/nero/workspace/java/tis-uber/data/libs/plugins/tis-datax-local-executor/WEB-INF/lib/*:/home/nero/workspace/java/tis-uber/tis-assemble/conf:/home/nero/workspace/java/tis-uber/web-start/lib/*,workingDir:.
09-02 10:32 dataX:mysql_test of dagSessionSpec:->oe_order_0.json->oe_order  ->oe_stu_course_order_1.json->oe_stu_course_order  ->oe_stu_course_2.json->oe_stu_course
09-02 10:32 dagSessionSpec:->oe_order_0.json->oe_order  ->oe_stu_course_order_1.json->oe_stu_course_order  ->oe_stu_course_2.json->oe_stu_course
09-02 10:32 process DataX job, dataXName:mysql_test,jobid:4,jobName:oe_stu_course_order_1.json/bxg1/oe_stu_course_order,allrows:-1
09-02 10:32 command:java -Ddata.dir=/home/nero/workspace/java/tis-uber/data -Denv_props=false -Dlog.dir=/home/nero/workspace/java/tis-uber/logs -Druntime=daily -Dlogback.configurationFile=logback-datax.xml -DexecTimeStamp=1693621974749 -DnotFetchFromCenterRepository=true -classpath /home/nero/workspace/java/tis-uber/tis-assemble/lib/*:/home/nero/workspace/java/tis-uber/data/libs/plugins/tis-datax-local-executor/WEB-INF/lib/*:/home/nero/workspace/java/tis-uber/tis-assemble/conf:/home/nero/workspace/java/tis-uber/web-start/lib/* com.qlangtech.tis.datax.DataxExecutor 4 oe_stu_course_order_1.json/bxg1/oe_stu_course_order mysql_test 127.0.0.1:56432 local -1 ap 3 1693621974749
09-02 10:33 dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
09-02 10:33 datax:mysql_test,jobName:oe_stu_course_order_1.json
com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
        at com.qlangtech.tis.datax.DataXJobSingleProcessorExecutor.consumeMessage(DataXJobSingleProcessorExecutor.java:132)
        at com.qlangtech.tis.plugin.datax.TaskExec$1.run(TaskExec.java:101)
        at com.qlangtech.tis.fullbuild.taskflow.DumpTask.run(DumpTask.java:56)
        at com.qlangtech.tis.fullbuild.taskflow.TISReactor$TaskImpl.run(TISReactor.java:142)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at com.qlangtech.tis.manage.impl.DataFlowAppSource$1.lambda$newThread$0(DataFlowAppSource.java:109)
        at java.lang.Thread.run(Unknown Source)
09-02 10:33 oe_stu_course_order_1.json
java.lang.RuntimeException: com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
        at com.qlangtech.tis.plugin.datax.TaskExec$1.run(TaskExec.java:112)
        at com.qlangtech.tis.fullbuild.taskflow.DumpTask.run(DumpTask.java:56)
        at com.qlangtech.tis.fullbuild.taskflow.TISReactor$TaskImpl.run(TISReactor.java:142)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at com.qlangtech.tis.manage.impl.DataFlowAppSource$1.lambda$newThread$0(DataFlowAppSource.java:109)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
        at com.qlangtech.tis.datax.DataXJobSingleProcessorExecutor.consumeMessage(DataXJobSingleProcessorExecutor.java:132)
        at com.qlangtech.tis.plugin.datax.TaskExec$1.run(TaskExec.java:101)
        ... 9 common frames omitted
09-02 10:33 process DataX job, dataXName:mysql_test,jobid:4,jobName:oe_order_0.json/bxg1/oe_order,allrows:-1
09-02 10:33 command:java -Ddata.dir=/home/nero/workspace/java/tis-uber/data -Denv_props=false -Dlog.dir=/home/nero/workspace/java/tis-uber/logs -Druntime=daily -Dlogback.configurationFile=logback-datax.xml -DexecTimeStamp=1693621974749 -DnotFetchFromCenterRepository=true -classpath /home/nero/workspace/java/tis-uber/tis-assemble/lib/*:/home/nero/workspace/java/tis-uber/data/libs/plugins/tis-datax-local-executor/WEB-INF/lib/*:/home/nero/workspace/java/tis-uber/tis-assemble/conf:/home/nero/workspace/java/tis-uber/web-start/lib/* com.qlangtech.tis.datax.DataxExecutor 4 oe_order_0.json/bxg1/oe_order mysql_test 127.0.0.1:56432 local -1 ap 4 1693621974749
09-02 10:33 dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
09-02 10:33 datax:mysql_test,jobName:oe_order_0.json
com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
        at com.qlangtech.tis.datax.DataXJobSingleProcessorExecutor.consumeMessage(DataXJobSingleProcessorExecutor.java:132)
        at com.qlangtech.tis.plugin.datax.TaskExec$1.run(TaskExec.java:101)
        at com.qlangtech.tis.fullbuild.taskflow.DumpTask.run(DumpTask.java:56)
        at com.qlangtech.tis.fullbuild.taskflow.TISReactor$TaskImpl.run(TISReactor.java:142)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at com.qlangtech.tis.manage.impl.DataFlowAppSource$1.lambda$newThread$0(DataFlowAppSource.java:109)
        at java.lang.Thread.run(Unknown Source)
09-02 10:33 oe_order_0.json
java.lang.RuntimeException: com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
        at com.qlangtech.tis.plugin.datax.TaskExec$1.run(TaskExec.java:112)
        at com.qlangtech.tis.fullbuild.taskflow.DumpTask.run(DumpTask.java:56)
        at com.qlangtech.tis.fullbuild.taskflow.TISReactor$TaskImpl.run(TISReactor.java:142)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at com.qlangtech.tis.manage.impl.DataFlowAppSource$1.lambda$newThread$0(DataFlowAppSource.java:109)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
        at com.qlangtech.tis.datax.DataXJobSingleProcessorExecutor.consumeMessage(DataXJobSingleProcessorExecutor.java:132)
        at com.qlangtech.tis.plugin.datax.TaskExec$1.run(TaskExec.java:101)
        ... 9 common frames omitted
09-02 10:33 process DataX job, dataXName:mysql_test,jobid:4,jobName:oe_stu_course_2.json/bxg1/oe_stu_course,allrows:-1
09-02 10:33 command:java -Ddata.dir=/home/nero/workspace/java/tis-uber/data -Denv_props=false -Dlog.dir=/home/nero/workspace/java/tis-uber/logs -Druntime=daily -Dlogback.configurationFile=logback-datax.xml -DexecTimeStamp=1693621974749 -DnotFetchFromCenterRepository=true -classpath /home/nero/workspace/java/tis-uber/tis-assemble/lib/*:/home/nero/workspace/java/tis-uber/data/libs/plugins/tis-datax-local-executor/WEB-INF/lib/*:/home/nero/workspace/java/tis-uber/tis-assemble/conf:/home/nero/workspace/java/tis-uber/web-start/lib/* com.qlangtech.tis.datax.DataxExecutor 4 oe_stu_course_2.json/bxg1/oe_stu_course mysql_test 127.0.0.1:56432 local -1 ap 5 1693621974749
09-02 10:33 dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
09-02 10:33 datax:mysql_test,jobName:oe_stu_course_2.json
com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
        at com.qlangtech.tis.datax.DataXJobSingleProcessorExecutor.consumeMessage(DataXJobSingleProcessorExecutor.java:132)
        at com.qlangtech.tis.plugin.datax.TaskExec$1.run(TaskExec.java:101)
        at com.qlangtech.tis.fullbuild.taskflow.DumpTask.run(DumpTask.java:56)
        at com.qlangtech.tis.fullbuild.taskflow.TISReactor$TaskImpl.run(TISReactor.java:142)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at com.qlangtech.tis.manage.impl.DataFlowAppSource$1.lambda$newThread$0(DataFlowAppSource.java:109)
        at java.lang.Thread.run(Unknown Source)
09-02 10:33 oe_stu_course_2.json
java.lang.RuntimeException: com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
        at com.qlangtech.tis.plugin.datax.TaskExec$1.run(TaskExec.java:112)
        at com.qlangtech.tis.fullbuild.taskflow.DumpTask.run(DumpTask.java:56)
        at com.qlangtech.tis.fullbuild.taskflow.TISReactor$TaskImpl.run(TISReactor.java:142)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at com.qlangtech.tis.manage.impl.DataFlowAppSource$1.lambda$newThread$0(DataFlowAppSource.java:109)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
        at com.qlangtech.tis.datax.DataXJobSingleProcessorExecutor.consumeMessage(DataXJobSingleProcessorExecutor.java:132)
        at com.qlangtech.tis.plugin.datax.TaskExec$1.run(TaskExec.java:101)
        ... 9 common frames omitted
09-02 10:33 taskid:4,phase:[join,dump] faild,reason:status.runningStatus.isComplete():com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
09-02 10:33 full build job is failed
09-02 10:33 status.runningStatus.isComplete():com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:mysql_test,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
```

**Comment by baisui1981** [comment]
看一下 是否和 https://github.com/datavane/tis/issues/260 相同原因，由于数据库没有密码导致的

**Comment by zerolbsony** [comment]
谢谢，解决了空指针的问题，但是还有报错。

**Comment by baisui1981** [comment]
> 看一下 是否和 #260 相同原因，由于数据库没有密码导致的

需要添加上 数据库密码，然后再重新编辑一下数据通道，不然最终的datax 配置不会变更
