### ISSUE TITLE
flink cdc mysql to kafka 任务空指针异常

### ISSUE THREAD

**Issue by zerolbsony** [datavane/tis#260]
<img width="1013" alt="截屏2023-09-02 上午11 51 17" src="https://github.com/datavane/tis/assets/5180779/271dec4e-aef5-40c4-a972-e6ad0fe0d034">
<img width="1269" alt="截屏2023-09-02 上午11 51 04" src="https://github.com/datavane/tis/assets/5180779/5103858d-66f9-4edc-94d4-ae764c81654e">
<img width="1222" alt="截屏2023-09-02 上午11 50 51" src="https://github.com/datavane/tis/assets/5180779/192bd6b3-cec8-41cc-8a57-4062004f1491">
<img width="1256" alt="截屏2023-09-02 上午11 50 37" src="https://github.com/datavane/tis/assets/5180779/c0970732-aa6d-4af0-b505-589e4d76687f">

错误日志如下：

``` shell
Caused by: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: java.lang.NullPointerException
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:158)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:82)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:117)
	at com.qlangtech.tis.plugins.flink.client.FlinkClient.submitJar(FlinkClient.java:90)
	at com.qlangtech.plugins.incr.flink.launch.FlinkTaskNodeController.deploy(FlinkTaskNodeController.java:167)
	at com.qlangtech.plugins.incr.flink.launch.FlinkTaskNodeController.deploy(FlinkTaskNodeController.java:137)
	at com.qlangtech.tis.coredefine.module.action.TISK8sDelegate.deploy(TISK8sDelegate.java:137)
	at com.qlangtech.tis.coredefine.module.action.CoreAction.doDeployIncrSyncChannal(CoreAction.java:548)
	... 124 more
Caused by: com.qlangtech.tis.async.message.client.consumer.MQConsumeException: java.lang.NullPointerException
	at com.qlangtech.plugins.incr.flink.cdc.mysql.FlinkCDCMysqlSourceFunction.start(FlinkCDCMysqlSourceFunction.java:207)
	at com.qlangtech.plugins.incr.flink.cdc.mysql.FlinkCDCMysqlSourceFunction.start(FlinkCDCMysqlSourceFunction.java:56)
	at com.qlangtech.plugins.incr.flink.TISFlinkCDCStart.deploy(TISFlinkCDCStart.java:154)
	at com.qlangtech.plugins.incr.flink.TISFlinkCDCStart.main(TISFlinkCDCStart.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	... 133 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.qlangtech.plugins.incr.flink.cdc.SourceChannel.getSourceFunction(SourceChannel.java:164)
	at com.qlangtech.plugins.incr.flink.cdc.SourceChannel.getSourceFunction(SourceChannel.java:69)
	at com.qlangtech.plugins.incr.flink.cdc.mysql.FlinkCDCMysqlSourceFunction.start(FlinkCDCMysqlSourceFunction.java:170)
	... 141 more
Caused by: java.lang.NullPointerException
	at org.apache.flink.util.Preconditions.checkNotNull(Preconditions.java:59)
	at com.ververica.cdc.connectors.mysql.MySqlSource$Builder.build(MySqlSource.java:173)
	at com.qlangtech.plugins.incr.flink.cdc.mysql.FlinkCDCMysqlSourceFunction.lambda$start$1(FlinkCDCMysqlSourceFunction.java:200)
	at com.qlangtech.plugins.incr.flink.cdc.SourceChannel.getSourceFunction(SourceChannel.java:158)
	... 143 more
```

**Comment by baisui1981** [comment]
收到 ，会尽快排查

**Comment by baisui1981** [comment]
该类已经 变成`@Deprecated` com.ververica.cdc.connectors.mysql.MySqlSource
需要该用：com.ververica.cdc.connectors.mysql.source.MySqlSource
