### ISSUE TITLE
MYSQL到佈署在K8S裡面的Starrocks發生錯

### ISSUE THREAD

**Issue by InchIK** [datavane/tis#269]
在寫入be時候會發生 
Caused by: java.net.UnknownHostException: starrockscluster-sample-be-2.starrockscluster-sample-be-search.starrocks.svc.cluster.local: 未知的名稱或服務

請問有甚麼方法可以解決這個問題?

以下log
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.lang.RuntimeException: Writing records to StarRocks failed.
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.close(StarRocksWriterManager.java:116)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.StarRocksWriter$Task.post(StarRocksWriter.java:135)
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:65)
	at java.lang.Thread.run(Thread.java:750)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer$TaskExecutor$1.run(TaskGroupContainer.java:426)
Caused by: java.lang.RuntimeException: Writing records to StarRocks failed.
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.checkFlushException(StarRocksWriterManager.java:192)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.waitAsyncFlushingDone(StarRocksWriterManager.java:153)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.flush(StarRocksWriterManager.java:101)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.close(StarRocksWriterManager.java:114)
	... 4 more
Caused by: java.io.IOException: java.net.UnknownHostException: starrockscluster-sample-be-2.starrockscluster-sample-be-search.starrocks.svc.cluster.local: 未知的名稱或服務
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.asyncFlush(StarRocksWriterManager.java:173)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.access$000(StarRocksWriterManager.java:21)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager$1.run(StarRocksWriterManager.java:137)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.UnknownHostException: starrockscluster-sample-be-2.starrockscluster-sample-be-search.starrocks.svc.cluster.local: 未知的名稱或服務
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:867)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:815)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1291)
	at java.net.InetAddress.getAllByName(InetAddress.java:1144)
	at java.net.InetAddress.getAllByName(InetAddress.java:1065)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksStreamLoadVisitor.doHttpPut(StarRocksStreamLoadVisitor.java:212)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksStreamLoadVisitor.doStreamLoad(StarRocksStreamLoadVisitor.java:66)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.asyncFlush(StarRocksWriterManager.java:166)
	... 3 more
 - java.lang.RuntimeException: Writing records to StarRocks failed.
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.close(StarRocksWriterManager.java:116)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.StarRocksWriter$Task.post(StarRocksWriter.java:135)
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:65)
	at java.lang.Thread.run(Thread.java:750)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer$TaskExecutor$1.run(TaskGroupContainer.java:426)
Caused by: java.lang.RuntimeException: Writing records to StarRocks failed.
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.checkFlushException(StarRocksWriterManager.java:192)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.waitAsyncFlushingDone(StarRocksWriterManager.java:153)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.flush(StarRocksWriterManager.java:101)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.close(StarRocksWriterManager.java:114)
	... 4 more
Caused by: java.io.IOException: java.net.UnknownHostException: starrockscluster-sample-be-2.starrockscluster-sample-be-search.starrocks.svc.cluster.local: 未知的名稱或服務
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.asyncFlush(StarRocksWriterManager.java:173)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.access$000(StarRocksWriterManager.java:21)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager$1.run(StarRocksWriterManager.java:137)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.UnknownHostException: starrockscluster-sample-be-2.starrockscluster-sample-be-search.starrocks.svc.cluster.local: 未知的名稱或服務
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:867)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:815)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1291)
	at java.net.InetAddress.getAllByName(InetAddress.java:1144)
	at java.net.InetAddress.getAllByName(InetAddress.java:1065)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksStreamLoadVisitor.doHttpPut(StarRocksStreamLoadVisitor.java:212)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksStreamLoadVisitor.doStreamLoad(StarRocksStreamLoadVisitor.java:66)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.manager.StarRocksWriterManager.asyncFlush(StarRocksWriterManager.java:166)
	... 3 more

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40)
	at com.starrocks.connector.datax.plugin.writer.starrockswriter.StarRocksWriter$Task.post(StarRocksWriter.java:137)
	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:65)
	at java.lang.Thread.run(Thread.java:750)
	at com.alibaba.datax.core.taskgroup.TaskGroupContainer$TaskExecutor$1.run(TaskGroupContainer.java:426)

**Comment by baisui1981** [comment]
starrock 部署的命令如下：
```shell
 docker run -d --net=host --name starrocks -p 8030:8030 -p 9030:9030 -p 8040:8040 registry.cn-hangzhou.aliyuncs.com/tis/starrocks  
```
特别地需要在命令行上添加 **--net=host** 参数，使用本地网络，不然docker内部执行streamload命令过程中执行一次redirect，返还给客户端一个docker内部的网络host地址导致，客户端无法访问。
