### ISSUE TITLE
分库分表同步报找不到表

### ISSUE THREAD

**Issue by charnet1019** [datavane/tis#283]
库名如下:
![image](https://github.com/datavane/tis/assets/18616254/d97a23ba-e5df-4490-9503-2b5bd83b7886)

表名如下:
delivery_order_0 ... 60
delivery_order_item_0 ... 60
order_0 ... 30
order_addr_0 ... 30
order_invoice_0 ... 30

点击设置后报错:
![image](https://github.com/datavane/tis/assets/18616254/d1769dde-05a6-41d9-a612-1a7b6d49436f)

通过Notebook可以查看到表:
![image](https://github.com/datavane/tis/assets/18616254/b5bf579b-8a4d-40ac-b023-ca9789734990)

日志：

```bash
2023-11-06 15:03:13 INFO  executeaction- com.qlangtech.tis.coredefine.module.action.PluginAction:doSubformDetailedClick
2023-11-06 15:03:13 ERROR  c.q.t.m.c.v.TisExceptionInterceptor- toJSONString error
com.alibaba.fastjson.JSONException: toJSONString error
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1012)
	at com.qlangtech.tis.trigger.util.JsonUtil.toString(JsonUtil.java:139)
	at com.qlangtech.tis.manage.common.valve.AjaxValve.buildResultStruct(AjaxValve.java:169)
	at com.qlangtech.tis.manage.common.valve.AjaxValve.writeInfo2Client(AjaxValve.java:115)
	at com.qlangtech.tis.manage.common.valve.AjaxValve.writeExecuteResult(AjaxValve.java:96)
	at com.qlangtech.tis.manage.common.valve.AjaxValve.doExecute(AjaxValve.java:78)
	at org.apache.struts2.result.StrutsResultSupport.execute(StrutsResultSupport.java:206)
	at com.opensymphony.xwork2.DefaultActionInvocation.executeResult(DefaultActionInvocation.java:375)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:279)
	at org.apache.struts2.interceptor.debugging.DebuggingInterceptor.intercept(DebuggingInterceptor.java:250)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:179)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:263)
	at org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:49)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.doIntercept(ConversionErrorInterceptor.java:142)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:137)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:137)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.StaticParametersInterceptor.intercept(StaticParametersInterceptor.java:201)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:67)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.interceptor.DateTextFieldInterceptor.intercept(DateTextFieldInterceptor.java:133)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:89)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:243)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor.intercept(ModelDrivenInterceptor.java:101)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.ScopedModelDrivenInterceptor.intercept(ScopedModelDrivenInterceptor.java:142)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.ChainingInterceptor.intercept(ChainingInterceptor.java:160)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:175)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:121)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:167)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:203)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:196)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.qlangtech.tis.manage.common.valve.OperationLogInterceptor.doIntercept(OperationLogInterceptor.java:64)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.qlangtech.tis.manage.common.valve.TisExceptionInterceptor.doIntercept(TisExceptionInterceptor.java:89)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.qlangtech.tis.manage.spring.aop.AuthorityCheckAdvice.doIntercept(AuthorityCheckAdvice.java:85)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:137)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
	at org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:48)
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:574)
	at org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79)
	at org.apache.struts2.dispatcher.servlet.StrutsServlet.service(StrutsServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1411)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
	at com.qlangtech.tis.manage.common.DefaultFilter.doFilter(DefaultFilter.java:169)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1630)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:567)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.alibaba.fastjson.JSONException: serializer write error
	at com.alibaba.fastjson.serializer.SerializeConfig$ObjectSerializerAdapter.write(SerializeConfig.java:73)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:542)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:542)
	at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:373)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:542)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:542)
	at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:542)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1004)
	... 102 common frames omitted
Caused by: java.io.IOException: java.lang.RuntimeException: java.lang.RuntimeException: com.qlangtech.tis.plugin.datax.SelectedTab.getDftPks()
	at com.qlangtech.tis.trigger.util.JsonUtil$1.write(JsonUtil.java:100)
	at com.alibaba.fastjson.serializer.SerializeConfig$ObjectSerializerAdapter.write(SerializeConfig.java:71)
	... 109 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.qlangtech.tis.plugin.datax.SelectedTab.getDftPks()
	at com.qlangtech.tis.trigger.util.JsonUtil$UnCacheString.getValue(JsonUtil.java:131)
	at com.qlangtech.tis.trigger.util.JsonUtil$1.write(JsonUtil.java:97)
	... 110 common frames omitted
Caused by: java.lang.RuntimeException: com.qlangtech.tis.plugin.datax.SelectedTab.getDftPks()
	at com.qlangtech.tis.extension.util.GroovyShellEvaluate.eval(GroovyShellEvaluate.java:170)
	at com.qlangtech.tis.extension.util.GroovyShellEvaluate.lambda$scriptEval$0(GroovyShellEvaluate.java:130)
	at com.qlangtech.tis.trigger.util.JsonUtil$UnCacheString.getValue(JsonUtil.java:129)
	... 111 common frames omitted
Caused by: java.lang.RuntimeException: TableNotFound{ dbId=mall4cloud_order_x,tableName='purchase_order_item_lang_0'}
	at com.qlangtech.tis.plugin.ds.BasicDataSourceFactory.getTableMetadata(BasicDataSourceFactory.java:120)
	at com.qlangtech.tis.plugin.datax.common.BasicDataXRdbmsReader.getTableMetadata(BasicDataXRdbmsReader.java:179)
	at com.qlangtech.tis.plugin.datax.SelectedTab.lambda$getContextTableColsStream$7(SelectedTab.java:265)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.qlangtech.tis.extension.impl.SuFormProperties$SuFormGetterContext.getContextAttr(SuFormProperties.java:313)
	at com.qlangtech.tis.plugin.datax.SelectedTab.getContextTableColsStream(SelectedTab.java:263)
	at com.qlangtech.tis.plugin.datax.SelectedTab.getContextTableCols(SelectedTab.java:246)
	at com.qlangtech.tis.plugin.datax.SelectedTab.getDftPks(SelectedTab.java:168)
	at com.qlangtech.tis.plugin.datax.SelectedTab$getDftPks.call(Unknown Source)
	at Script23.run(Script23.groovy:1)
	at com.qlangtech.tis.extension.util.GroovyShellEvaluate.eval(GroovyShellEvaluate.java:168)
	... 113 common frames omitted
Caused by: com.qlangtech.tis.plugin.ds.TableNotFoundException: null
	at com.qlangtech.tis.plugin.ds.DataSourceFactory.parseTableColMeta(DataSourceFactory.java:199)
	at com.qlangtech.tis.plugin.ds.DataSourceFactory.lambda$parseTableColMeta$0(DataSourceFactory.java:331)
	at com.qlangtech.tis.plugin.ds.DataSourceFactory.validateConnection(DataSourceFactory.java:117)
	at com.qlangtech.tis.plugin.ds.DataSourceFactory.parseTableColMeta(DataSourceFactory.java:330)
	at com.qlangtech.tis.plugin.ds.BasicDataSourceFactory.parseTableColMeta(BasicDataSourceFactory.java:140)
	at com.qlangtech.tis.plugin.ds.BasicDataSourceFactory.lambda$getTableMetadata$1(BasicDataSourceFactory.java:110)
	at com.qlangtech.tis.plugin.ds.DBConfig.vistDbName(DBConfig.java:130)
	at com.qlangtech.tis.plugin.ds.BasicDataSourceFactory.getTableMetadata(BasicDataSourceFactory.java:109)
	... 123 common frames omitted
```

**Comment by baisui1981** [comment]
```
delivery_order_0 ... 60
delivery_order_item_0 ... 60
order_0 ... 30
order_addr_0 ... 30
order_invoice_0 ... 30
```
根据您所列的表和 异常信息中展示的表名`purchase_order_item_lang_0` 并不在 这些表中
```
mall4cloud_order_x,tableName='purchase_order_item_lang_0
```
是不是哪儿有出入？

**Comment by charnet1019** [comment]
有这个表，我没有全部列出来发自我的手机-------- 原始邮件 --------发件人： 百岁 ***@***.***>日期： 2023年11月6日周一 18:20收件人： datavane/tis ***@***.***>抄送： charnet1019 ***@***.***>, Author ***@***.***>主    题： Re: [datavane/tis] 分库分表同步报找不到表 (Issue #283)
delivery_order_0 ... 60
delivery_order_item_0 ... 60
order_0 ... 30
order_addr_0 ... 30
order_invoice_0 ... 30

根据您所列的表和 异常信息中展示的表名purchase_order_item_lang_0 并不在 这些表中
mall4cloud_order_x,tableName='purchase_order_item_lang_0

是不是哪儿有出入？

**Comment by charnet1019** [comment]
> ```
> delivery_order_0 ... 60
> delivery_order_item_0 ... 60
> order_0 ... 30
> order_addr_0 ... 30
> order_invoice_0 ... 30
> ```
> 
> 根据您所列的表和 异常信息中展示的表名`purchase_order_item_lang_0` 并不在 这些表中
> 
> ```
> mall4cloud_order_x,tableName='purchase_order_item_lang_0
> ```
> 
> 是不是哪儿有出入？猜测，是不是您的库里面只有部分表进行了分表 而像 `purchase_order_item_lang` 这个表并没有进行分表？

![image](https://github.com/datavane/tis/assets/18616254/0f289342-db54-447f-80e8-426d2a3faca7)
是有做分表的，但其中undo_log没有做

**Comment by charnet1019** [comment]
这个是完整的表名
![image](https://github.com/datavane/tis/assets/18616254/1c107c22-bd68-4ac7-9245-ac72cafa172f)

**Comment by charnet1019** [comment]
实际有这么多的分表，已经把没有分表的undo_log排除了，设置任何一个表都会提示找不到表，但在Nodebook中使用tables则可以正常显示所有的分表

![image](https://github.com/datavane/tis/assets/18616254/9f3d45d6-8e3b-4b14-8a31-bcdf2dba09d1)
![image](https://github.com/datavane/tis/assets/18616254/6fe756b4-4336-4e6b-97c1-e6db3b8d6a2c)

**Comment by baisui1981** [comment]
我怀疑`purchase_order_item_lang_0 ` 这个分表，并不是每个**分库** 中都存在，可能某几个分库中不存在的情况下 是会报这个异常的，您确认一下

**Comment by charnet1019** [comment]
> 我怀疑`purchase_order_item_lang_0 ` 这个分表，并不是每个**分库** 中都存在，可能某几个分库中不存在的情况下 是会报这个异常的，您确认一下

每个库中都有对应的表，表的数量和结构都是一样的，设置任何一个分表都会提示对应的表找不到比较奇怪

会不会是因这个分表规则的问题，这个我没有填是用的默认的
![image](https://github.com/datavane/tis/assets/18616254/b5b1430f-7750-44fc-9b28-b550d18b7046)

**Comment by baisui1981** [comment]
稍等 ，我本地试试，我微信：16660356

**Comment by baisui1981** [comment]
https://github.com/datavane/tis/blob/da8a60a12ab98d00c6b3bcf65625030ca9c203c0/tis-plugin/src/main/java/com/qlangtech/tis/plugin/ds/DataSourceFactory.java#L52

``` java
try (ResultSet tables = metaData1.getTables(null, getDbSchema(), table.getTableName(), null)) {
}
```
找到原因了 mysql8 驱动取表元数据信息 getTables 方法的第二个参数必须要用户传dbname，而
