### ISSUE TITLE
管道创建流程中更改端类型会出错

### ISSUE THREAD

**Issue by baisui1981** [datavane/tis#312]
1. 在pipeline创建阶段，当用户先选择 mysql-> doris 类型的同步，选择完表，
2. 然后，回退到端类型选择页面，重新选择了 mysql-> mysql，再进入下一步选择页面节点机会出错

错误如下：
``` shell
Caused by: java.lang.RuntimeException: fetchKeys:seqKey,primaryKeys,name,where,cols，hasKeys:KEY_SOURCE_PROPS,KEY_FIELD_COLS,KEY_FIELD_PRIMARY_KEYS,sourceProps,name,primaryKeys,where,cols,MSG_ERROR_NAME_DUPLICATE
	at com.qlangtech.tis.extension.impl.RootFormProperties.getInstancePropsJson(RootFormProperties.java:82)
	at com.qlangtech.tis.util.DescribableJSON.getItemJson(DescribableJSON.java:85)
	at com.qlangtech.tis.extension.impl.SuFormProperties.addSubItems(SuFormProperties.java:291)
	at com.qlangtech.tis.extension.impl.BaseSubFormProperties.createSubFormVals(BaseSubFormProperties.java:159)
	... 129 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Can not set com.qlangtech.tis.plugin.datax.seq.SeqKey field com.qlangtech.tis.plugin.datax.doris.DorisSelectedTab.seqKey to com.qlangtech.tis.plugin.datax.SelectedTab
	at com.qlangtech.tis.extension.impl.PropertyType.getVal(PropertyType.java:451)
	at com.qlangtech.tis.extension.impl.RootFormProperties.getInstancePropsJson(RootFormProperties.java:68)
	... 132 more
Caused by: java.lang.IllegalArgumentException: Can not set com.qlangtech.tis.plugin.datax.seq.SeqKey field com.qlangtech.tis.plugin.datax.doris.DorisSelectedTab.seqKey to com.qlangtech.tis.plugin.datax.SelectedTab
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
	at java.lang.reflect.Field.get(Field.java:393)
	at com.qlangtech.tis.extension.impl.PropertyType.getVal(PropertyType.java:442)
	... 133 more
```

**Comment by baisui1981** [comment]
已经修改了
