### ISSUE TITLE
mongo->mysql通道构建发生报错

### ISSUE THREAD

**Issue by qq249284465** [datavane/tis#326]
``` shell
06-07 11:20  start component:FullDump,end component:FullDump
06-07 11:20  component description:
06-07 11:20  JOIN:0
06-07 11:20  FullDump:0
06-07 11:20  description end
06-07 11:20  execute [dump,join]:0[0,0]
06-07 11:20  phase:[dump,join] start ,taskid:13
06-07 11:20  target xstream file is not exist:/data/tis/tis-uber/data/cfg_repo/tis_plugin_config/jobworker/datax-worker/com.qlangtech.tis.datax.job.DataXJobWorker.xml
06-07 11:20  target xstream file is not exist:/data/tis/tis-uber/data/cfg_repo/tis_plugin_config/jobworker/datax-worker/com.qlangtech.tis.datax.job.DataXJobWorker.xml
06-07 11:20  class:class com.qlangtech.tis.plugin.datax.DataXMongodbReader relevant descriptor can not be null
java.lang.NullPointerException: class:class com.qlangtech.tis.plugin.datax.DataXMongodbReader relevant descriptor can not be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.qlangtech.tis.datax.impl.DataxReader.getDescriptor(DataxReader.java:348)
	at com.qlangtech.tis.datax.impl.DataxReader$2.afterDeserialize(DataxReader.java:200)
	at com.qlangtech.tis.datax.impl.DataxReader$2.afterDeserialize(DataxReader.java:195)
	at com.qlangtech.tis.plugin.PluginStore.lambda$load$4(PluginStore.java:421)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.qlangtech.tis.plugin.PluginStore.load(PluginStore.java:419)
	at com.qlangtech.tis.plugin.PluginStore.getPlugins(PluginStore.java:132)
	at com.qlangtech.tis.plugin.KeyedPluginStore.getPlugins(KeyedPluginStore.java:151)
	at com.qlangtech.tis.plugin.PluginStore.getPlugin(PluginStore.java:180)
	at com.qlangtech.tis.datax.impl.DataxReader.load(DataxReader.java:310)
	at com.qlangtech.tis.datax.impl.DataxReader.load(DataxReader.java:292)
	at com.qlangtech.tis.datax.impl.DataxProcessor.getReader(DataxProcessor.java:285)
	at com.qlangtech.tis.sql.parser.DAGSessionSpec.createDAGSessionSpec(DAGSessionSpec.java:149)
	at com.qlangtech.tis.exec.datax.DataXExecuteInterceptor.execute(DataXExecuteInterceptor.java:74)
	at com.qlangtech.tis.exec.impl.TrackableExecuteInterceptor.intercept(TrackableExecuteInterceptor.java:122)
	at com.qlangtech.tis.exec.AbstractActionInvocation.invoke(AbstractActionInvocation.java:149)
	at com.qlangtech.tis.order.center.IndexSwapTaskflowLauncher.startWork(IndexSwapTaskflowLauncher.java:282)
	at com.qlangtech.tis.fullbuild.servlet.TisServlet.startWork(TisServlet.java:440)
	at com.qlangtech.tis.fullbuild.servlet.TisServlet.lambda$doPost$0(TisServlet.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
06-07 11:20  java.lang.NullPointerException: class:class com.qlangtech.tis.plugin.datax.DataXMongodbReader relevant descriptor can not be null
java.lang.RuntimeException: java.lang.NullPointerException: class:class com.qlangtech.tis.plugin.datax.DataXMongodbReader relevant descriptor can not be null
	at com.qlangtech.tis.fullbuild.servlet.TisServlet.lambda$doPost$0(TisServlet.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: class:class com.qlangtech.tis.plugin.datax.DataXMongodbReader relevant descriptor can not be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.qlangtech.tis.datax.impl.DataxReader.getDescriptor(DataxReader.java:348)
	at com.qlangtech.tis.datax.impl.DataxReader$2.afterDeserialize(DataxReader.java:200)
	at com.qlangtech.tis.datax.impl.DataxReader$2.afterDeserialize(DataxReader.java:195)
	at com.qlangtech.tis.plugin.PluginStore.lambda$load$4(PluginStore.java:421)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.qlangtech.tis.plugin.PluginStore.load(PluginStore.java:419)
	at com.qlangtech.tis.plugin.PluginStore.getPlugins(PluginStore.java:132)
	at com.qlangtech.tis.plugin.KeyedPluginStore.getPlugins(KeyedPluginStore.java:151)
	at com.qlangtech.tis.plugin.PluginStore.getPlugin(PluginStore.java:180)
	at com.qlangtech.tis.datax.impl.DataxReader.load(DataxReader.java:310)
	at com.qlangtech.tis.datax.impl.DataxReader.load(DataxReader.java:292)
	at com.qlangtech.tis.datax.impl.DataxProcessor.getReader(DataxProcessor.java:285)
	at com.qlangtech.tis.sql.parser.DAGSessionSpec.createDAGSessionSpec(DAGSessionSpec.java:149)
	at com.qlangtech.tis.exec.datax.DataXExecuteInterceptor.execute(DataXExecuteInterceptor.java:74)
	at com.qlangtech.tis.exec.impl.TrackableExecuteInterceptor.intercept(TrackableExecuteInterceptor.java:122)
	at com.qlangtech.tis.exec.AbstractActionInvocation.invoke(AbstractActionInvocation.java:149)
	at com.qlangtech.tis.order.center.IndexSwapTaskflowLauncher.startWork(IndexSwapTaskflowLauncher.java:282)
	at com.qlangtech.tis.fullbuild.servlet.TisServlet.startWork(TisServlet.java:440)
	at com.qlangtech.tis.fullbuild.servlet.TisServlet.lambda$doPost$0(TisServlet.java:209)
	... 5 common frames omitted
```

**Comment by baisui1981** [comment]
应该是由于刚装了上了TIS的插件，assemble节点还没有生效，将TIS重启一下应该就好了。下个版本中会修复

**Comment by qq249284465** [comment]
感谢回复 这个确实重启后得到了解决 
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年6月7日 11:45
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [datavane/tis] mongo->mysql通道构建发生报错 (Issue #326)
        
      
    
  

应该是由于刚装了上了TIS的插件，assemble节点还没有生效，将TIS重启一下应该就好了。下个版本中会修复

**Comment by qq249284465** [comment]
另外 我还想问一下 现在可以支持mongodb-》mysql(doris)的实时同步吗
        我测试了下貌似不行
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年6月7日 11:45
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [datavane/tis] mongo->mysql通道构建发生报错 (Issue #326)
        
      
    
  

应该是由于刚装了上了TIS的插件，assemble节点还没有生效，将TIS重启一下应该就好了。下个版本中会修复

**Comment by baisui1981** [comment]
> 另外 我还想问一下 现在可以支持mongodb-》mysql(doris)的实时同步吗 我测试了下貌似不行 ***@***.***

目前只支持批量同步，实时同步还要等后续版本中添加
