### ISSUE TITLE
使用dataX同步Doris报错

### ISSUE THREAD

**Issue by ztzhenshuai** [datavane/tis#348]
我的数据源配置在DataX环境成功连接，但使用tis时报错无法连接。同时想知道如何配置定时同步数据呀
``` shell
Caused by: java.lang.RuntimeException: Writing records to Doris failed.
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.checkFlushException(DorisWriterManager.java:189)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.waitAsyncFlushingDone(DorisWriterManager.java:150)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.flush(DorisWriterManager.java:98)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.close(DorisWriterManager.java:111)
        ... 4 more
Caused by: java.io.IOException: org.apache.http.conn.HttpHostConnectException: Connect to 172.16.30.3:8040 [/172.16.30.3] failed: 连接超时 (Connection timed out)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.asyncFlush(DorisWriterManager.java:170)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.access$000(DorisWriterManager.java:19)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager$1.run(DorisWriterManager.java:134)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by baisui1981** [comment]
请确认doris BE节点部署是否正常

**Comment by ztzhenshuai** [comment]
一切正常，都是alive状态，并且可以通过dataX读写，是需要做额外配置吗

**Comment by baisui1981** [comment]
看 172.16.30.3:8040 这个ip就不对，你启动的doris 是用 docker，这个ip是docker 内网ip，TIS部署在 docker 网络外部，确实是无法连上这个ip的

**Comment by ztzhenshuai** [comment]
sorry，忘了回复已经解决了，Doris配置了二级IP，所以需要对tis中dataX进行配置就可以了
