### ISSUE TITLE
flink 启动立即失败，报告无法分配足够slot资源

### ISSUE THREAD

**Issue by baisui1981** [datavane/tis#362]
flink 启动立即失败，报告无法分配足够slot资源
``` shell
org.apache.flink.util.FlinkExpectedException: TaskExecutor pekko.tcp://flink@10.100.1.233:34565/user/rpc/taskmanager_0 has no more allocated slots for job 8e4ecfe26ee56bb0bb7a688fe4ffa584.
        at org.apache.flink.runtime.taskexecutor.TaskExecutor.closeJobManagerConnectionIfNoAllocatedResources(TaskExecutor.java:2056) ~[flink-dist-tis-1.18.1.jar:tis-1.18.1]
        at org.apache.flink.runtime.taskexecutor.TaskExecutor.freeSlotInternal(TaskExecutor.java:2032) ~[flink-dist-tis-1.18.1.jar:tis-1.18.1]
        at org.apache.flink.runtime.taskexecutor.TaskExecutor.timeoutSlot(TaskExecutor.java:2070) ~[flink-dist-tis-1.18.1.jar:tis-1.18.1]
        at org.apache.flink.runtime.taskexecutor.TaskExecutor.access$3600(TaskExecutor.java:188) ~[flink-dist-tis-1.18.1.jar:tis-1.18.1]
        at org.apache.flink.runtime.taskexecutor.TaskExecutor$SlotActionsImpl.lambda$timeoutSlot$1(TaskExecutor.java:2514) ~[flink-dist-tis-1.18.1.jar:tis-1.18.1]
        at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.l
        at org.apache.flink.runtime.concurrent.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-dist-tis-1.18.1.jar:tis-1.18.1]
        at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRunAsync(PekkoRpcActor.java:451) ~[flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRpcMessage(PekkoRpcActor.java:218) ~[flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleMessage(PekkoRpcActor.java:168) ~[flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:33) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:29) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at scala.PartialFunction.applyOrElse(PartialFunction.scala:127) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at org.apache.pekko.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:29) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]                                   ambda$handleRunAsync$4(PekkoRpcActor.java:451) ~[flink-rpc-at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:545) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at org.apache.pekko.actor.AbstractActor.aroundReceive(AbstractActor.scala:229) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253) [flink-rpc-akka6d6de83d-177c-4326-894e-3c31928b611b.jar:tis-1.18.1]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_412]                                
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_412]                    
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_412] 
```
原因分析：
![mmexport1726792748824](https://github.com/user-attachments/assets/9bb3ddd9-2a63-4a80-8ff0-550a88a04e60)

发现taskmanager.host确实被 ansible初始化脚本删除了
https://github.com/qlangtech/tis-ansible/blob/26fa6fa67493474dd9c0bb5fea9ac84078349e38/roles/flink/tasks/main.yml#L20

**Comment by baisui1981** [comment]
虽然改回来了 ，需要回归一下 flink k8s 方式部署方式执行是否正常
