### ISSUE TITLE
MongoDB作为数据源不支持Transformer功能

### ISSUE THREAD

**Issue by baisui1981** [datavane/tis#371]
## 操作截图

![截屏2024-10-15 16 16 17](https://github.com/user-attachments/assets/6bf0ef14-32b2-4648-a8ba-26c03f045334)

## 报以下错误
``` shell
Caused by: java.lang.RuntimeException: com.qlangtech.tis.plugin.datax.transformer.impl.AbstractFromColumnUDFDefinition.colsCandidate()
	at com.qlangtech.tis.extension.util.GroovyShellEvaluate.eval(GroovyShellEvaluate.java:112)
	at com.qlangtech.tis.extension.util.GroovyShellEvaluate.lambda$scriptEval$0(GroovyShellEvaluate.java:85)
	at com.qlangtech.tis.trigger.util.UnCacheString.getValue(UnCacheString.java:39)
	... 161 more
Caused by: java.lang.UnsupportedOperationException: getDbConfig
	at com.qlangtech.tis.plugin.ds.mangodb.MangoDBDataSourceFactory.getDbConfig(MangoDBDataSourceFactory.java:144)
	at com.qlangtech.tis.plugin.datax.common.TableColsMeta.<init>(TableColsMeta.java:52)
	at com.qlangtech.tis.plugin.datax.common.BasicDataXRdbmsReader.getTabsMeta(BasicDataXRdbmsReader.java:211)
	at com.qlangtech.tis.plugin.datax.common.BasicDataXRdbmsReader.fillSelectedTabMeta(BasicDataXRdbmsReader.java:162)
	at com.qlangtech.tis.plugin.datax.common.BasicDataXRdbmsReader.fillSelectedTabMeta(BasicDataXRdbmsReader.java:150)
	at com.qlangtech.tis.plugin.datax.SelectedTab.lambda$getContextTableColsStream$8(SelectedTab.java:319)
	at com.qlangtech.tis.plugin.datax.ThreadCacheTableCols.getSelectedCols(ThreadCacheTableCols.java:54)
	at com.qlangtech.tis.plugin.datax.SelectedTab.getSelectedCols(SelectedTab.java:161)
	at com.qlangtech.tis.plugin.datax.transformer.UDFDefinition.colsCandidate(UDFDefinition.java:79)
	at com.qlangtech.tis.plugin.datax.transformer.UDFDefinition$colsCandidate.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at Script17.run(Script17.groovy:1)
	at com.qlangtech.tis.extension.util.GroovyShellEvaluate.eval(GroovyShellEvaluate.java:110)
```

**Comment by baisui1981** [comment]
已经实现了
