### ISSUE TITLE
利用FTP将CSV文件导入doris 配置流程出错

### ISSUE THREAD

**Issue by baisui1981** [datavane/tis#404]
<img width="1849" alt="WechatIMG3529" src="https://github.com/user-attachments/assets/b93941e4-b478-4c8f-92fa-a2a1e75b95c8" />
在配置流程中出现以下错误：

```shell
java.lang.UnsupportedOperationException
at com, alangtech,. tis. plugin, ds, IdlistElementCreatorFactory. parsePostMcols(IdlistElementCreatorFactory. java:53)at com. qlangtech. tis. coredefine. module. action. DataxAction$7. validate(DataxAction. java:1498)at com. glangtech.tis.plugin. annotation.Validator.validate(Validator. java:170)
at com. qlangtech. tis. plugin. annotation. Validator. validateAllFieldRules(Validator. java:305)
at com. glangtech. tis.plugin. annotation. Validator. validate(Validator. java:277)
at com. glangtech. tis. coredefine. module. action. DataxAction. doSaveriterColsMeta(DataxAction. java:1466)at java. base/idk. internal.reflect,NativeMethodAccessorImpl, invoke0 (Native Method)at java. base/idk. internal. reflect. NativeMethodAccessorImpl. invoke (NativeMethodAccessorImpl. java:62)
at java. base/ jdk. internal. reflect. DelegatingMethodAccessorImpl. invoke(DelegatingMethodAccessorImpl. java:43)
at java. base/java. lang.reflect.Method. invoke (Method. java:566)
at com. qlangtech. tis. runtime. module.action.BasicModule.execute(BasicModule. java:184)
at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
at java. base/jdk. internal. reflect. DelegatingMethodAccessorImpl. invoke(DelegatingMethodccessorImpl. java:43)
at java.base/java.lang.reflect.Method.invoke (Method. java:566)
at ognl.0gnlRuntime.invokeMethodInsideSandbox(0gnlRuntime. java: 1245)
at ognl.0gnlRuntime.invokeMethod(OgnlRuntime. java:1230)
at ognl.0gnlRuntime.callAppropriateMethod(OgnlRuntime. java:1958)
at ognl.0biectMethodAccessor,callMethod(0biectMethodAccessor, iaya:68
at com. opensymphony. xwork2. ognl. accessor. XWorkMethodAccessor. callMethodwithebugInfo(XWorkMethodAccessor. java:98)at com. opensymphony. xwork2. ognl. accessor. XWorkMethodAccessor. callMethod(xWorkMethodAccessor. java:90)
at ognl.0gnlRuntime.callMethod(OgnlRuntime. java:2034)
at ognl.ASTMethod.getValueBody(ASTMethod. java:97)
at ognl.SimpleNode.evaluateGetValueBody(SimpleNode. java:212)
at ognl.SimpleNode.getValue(SimpleNode. java:258)
at ognl.0gnl.getValue(0gnl. java:586)
at com.opensymphony.xwork2.ognl.0gnlUtil.ognlGet (0gnlUtil. java:596)
```

**Comment by baisui1981** [comment]
<table style={{width: '100%', display: 'table'}}  border='1'>
<thead><tr><th rowspan='2'>类�~^~K</th><th colspan='2'>�~I��~G~O(DataX)</th><th colspan='2'>�~^�~W�</th></tr>
<tr><th width='20%'>读</th><th width='20%'>�~F~Y</th><th width='20%'>Source</th><th width='20%'>Sink</th></tr>
</thead><tbody>
<tr>
<td class='endtype-name'>MongoDB</td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxmongodbreader'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxmongodbwriter'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link flink-cdc-color'><Link to={plugins.metadata.permalink+'#comqlangtechpluginsincrflinkcdcmongdbflinkcdcmongodbsourcefactory'}>1</Link></i></td><td></td></tr>
<tr>
<td class='endtype-name'>Cassandra</td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxcassandrareader'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxcassandrawriter'}>1</Link></i></td><td></td><td></td></tr>
<tr>
<td class='endtype-name'>ElasticSearch</td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxelasticsearchwriter'}>1</Link></i></td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link tis-color'><Link to={plugins.metadata.permalink+'#comqlangtechtispluginsincrflinkconnectorelasticsearch7elasticsearchsinkfactory'}>1</Link></i></td></tr>
<tr>
<td class='endtype-name'>TDFS</td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxdfsreader'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxdfswriter'}>1</Link></i></td><td></td><td></td></tr>
<tr>
<td class='endtype-name'>Kafka</td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtispluginsdataxkafkawriterdataxkafkawriter'}>1</Link></i></td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link chunjun-color'><Link to={plugins.metadata.permalink+'#comqlangtechtispluginsincrflinkchunjunkafkasinkchujunkafkasinkfactory'}>1</Link></i></td></tr>
<tr>
<td class='endtype-name'>Oracle</td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxoraclereader'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxoraclewriter'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link flink-cdc-color'><Link to={plugins.metadata.permalink+'#comqlangtechpluginsincrflinkcdcoracleflinkcdcoraclesourcefactory'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link chunjun-color'><Link to={plugins.metadata.permalink+'#comqlangtechpluginsincrflinkchunjunoraclesinkchunjunoraclesinkfactory'}>1</Link></i></td></tr>
<tr>
<td class='endtype-name'>MariaDB</td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxmariareader'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxmariawriter'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link flink-cdc-color'><Link to={plugins.metadata.permalink+'#comqlangtechtispluginsincrflinkcdcmariaflinkcdcmariadbsourcefactory'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link chunjun-color'><Link to={plugins.metadata.permalink+'#comqlangtechtispluginsincrflinkmariasinkmariadbsinkfactory'}>1</Link></i></td></tr>
<tr>
<td class='endtype-name'>SqlServer</td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxsqlserverreader'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxsqlserverwriter'}>1</Link></i></td><td></td><td></td></tr>
<tr>
<td class='endtype-name'>DaMeng</td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdamengreaderdataxdamengreader'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdamengwriterdataxdamengwriter'}>1</Link></i></td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link chunjun-color'><Link to={plugins.metadata.permalink+'#comqlangtechpluginsincrflinkchunjundamengsinkchunjundamengsinkfactory'}>1</Link></i></td></tr>
<tr>
<td class='endtype-name'>RocketMQ</td><td></td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link tis-color'><Link to={plugins.metadata.permalink+'#comqlangtechasyncmessageclientconsumerrocketmqlistenerfactory'}>1</Link></i></td><td></td></tr>
<tr>
<td class='endtype-name'>AliyunODPS</td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxodpswriter'}>1</Link></i></td><td></td><td></td></tr>
<tr>
<td class='endtype-name'>Postgres</td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxpostgresqlreader'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxpostgresqlwriter'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link flink-cdc-color'><Link to={plugins.metadata.permalink+'#comqlangtechpluginsincrflinkcdcpostgresqlflinkcdcpostresqlsourcefactory'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link chunjun-color'><Link to={plugins.metadata.permalink+'#comqlangtechpluginsincrflinkchunjunpostgresqlsinkchunjunpostgresqlsinkfactory'}>1</Link></i></td></tr>
<tr>
<td class='endtype-name'>Spark</td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxsparkwriter'}>1</Link></i></td><td></td><td></td></tr>
<tr>
<td class='endtype-name'>Clickhouse</td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxclickhousewriter'}>1</Link></i></td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link chunjun-color'><Link to={plugins.metadata.permalink+'#comqlangtechpluginsincrflinkchunjunclickhousesinkchunjunclickhousesinkfactory'}>1</Link></i></td></tr>
<tr>
<td class='endtype-name'>StarRocks</td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxstarrocksdataxstarrockswriter'}>1</Link></i></td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link chunjun-color'><Link to={plugins.metadata.permalink+'#comqlangtechtispluginsincrflinkchunjunstarrockssinkchunjunstarrockssinkfactory'}>1</Link></i></td></tr>
<tr>
<td class='endtype-name'>HiveMetaStore</td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtishivereaderdataxhivereader'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxhivewriter'}>1</Link></i></td><td></td><td></td></tr>
<tr>
<td class='endtype-name'>Doris</td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdorisdataxdoriswriter'}>1</Link></i></td><td></td><td><i className={clsx('tis-check')}></i><i className='plugin-link chunjun-color'><Link to={plugins.metadata.permalink+'#comqlangtechpluginsincrflinkchunjundorissinkchunjundorissinkfactory'}>1</Link></i></td></tr>
<tr>
<td class='endtype-name'>MySQL</td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxmysqlreader'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link datax-color'><Link to={plugins.metadata.permalink+'#comqlangtechtisplugindataxdataxmysqlwriter'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link flink-cdc-color'><Link to={plugins.metadata.permalink+'#comqlangtechtispluginsincrflinkcdcmysqlflinkcdcmysqlsourcefactory'}>1</Link></i></td><td><i className={clsx('tis-check')}></i><i className='plugin-link chunjun-color'><Link to={plugins.metadata.permalink+'#comqlangtechtispluginsincrflinkconnectorsinkmysqlsinkfactory'}>1</Link></i></td></tr>
</tbody>
</table>

**Comment by tilepotter** [comment]
同样的问题，有没有解决了
![微信图片_20250116110515](https://github.com/user-attachments/assets/1c27bd8a-6a1a-4542-83f8-39907ad13e4f)

**Comment by baisui1981** [comment]
> 同样的问题，有没有解决了 ![微信图片_20250116110515](https://github.com/user-attachments/assets/1c27bd8a-6a1a-4542-83f8-39907ad13e4f)

4.1.0 中已经搞定了，等待发布
